### ISSUE TITLE
部署docker-compose方式报错

### ISSUE THREAD

**Issue by qkxwxy123** [Hello-hao/Tbed#61]
部署后访问如图错误
![1](https://user-images.githubusercontent.com/49123409/236656220-66c16874-e8d1-444a-878c-f0e7cfc72c4c.png)
应该是哪里问题呢。

**Comment by wangtao94** [comment]
报错+1

**Comment by Hello-hao** [comment]
什么系统？如果你在群里，可以私聊我，说一下具体报错的过程

**Comment by Hello-hao** [comment]
抱歉，是因为群满了，你现在可以加，有两个位置

**Comment by Zhen-Bo** [comment]
雖然不知道是不是同原因
不過我也是在 Synology 上使用會產生跟樓主一樣的錯誤
機型: DS1621+
DSM: 7.2 - 64561
套件版本:  container manager 20.10.23-1405
frontend subdomain: pic
backend subdomain: pic-server
域名託管商: cloudflare free
router: WRX 560
port frowarding: only 443

步驟:
1. dsm 自帶的 nginx 設定 proxy
  - pic -> 10089
  - pic-server -> 10089
2. 使用控制台內工具向 let's encrypt 申請兩個憑證, pic 子域名的對應 pic, pic-server 子域名的對應 pic-server
3. 訪問 pic 子域名(前端), 有三個打像後端的 api 被阻擋, 顯示錯誤 mixed-content
  1. http://pic-server.example.com/webInfo?16855432438850.32486561410600844657
  2. http://pic-server.example.com/getUploadInfo?16855432439420.4929950554563373771525
  3. http://pic-server.example.com/getUploadInfo?16855432439420.4929950554563373771525
![image](https://github.com/Hello-hao/Tbed/assets/30999421/e6112fec-9d2e-4cef-b9bc-ed862206630f)

**Comment by Zhen-Bo** [comment]
目測原因: 域名填寫錯誤
![image](https://github.com/Hello-hao/Tbed/assets/30999421/95663083-eba9-49ff-96cd-78805b1a8cc7)
為啥你請求的域名是: http://example.top:10089/$%7Bhttp://127.0.0.1:10089%7D/webInfo
解過來後是:  http://example.top:10089/${http://127.0.0.1:10089}/webInfo
感覺像是 `${}` 的參數被你當成字串處理了
而且更何況妳都有一 top 域名了, 為何網址列中還會有 `http://127.0.0.1:10089`

**Comment by Zhen-Bo** [comment]
或是你可以公開一下你的 docker-compose 沒有詳細的啟動檔案有點難幫你通靈出問題

**Comment by itodouble** [comment]
我也遇到那个域名的问题了
docker-compose.yml
```yml
version: "3"
services:
  tbed-free:
    image: hellohao/tbed-free:20230622
    container_name: tbed
    ports:
      - "10088:10088"
      - "10089:10089"
    volumes:
      - ./data/:/HellohaoData/
    environment:
      MYSQL_URL: jdbc:mysql://xxxxx.mysql.rds.aliyuncs.com/tbed?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
      MYSQL_USER: xxxxx
      MYSQL_PASS: xxxxx
      HELLOHAO_WEB_HOST: https://tbed.xxx.top
      HELLOHAO_SERVER_HOST: https://tbeds.xxxxxx.top
```

nginx-tbed.conf
```conf
server {
    listen       443 http2;
    server_name  tbed.xxxx.top;

    location / {
        proxy_set_header   Host    $host;
        proxy_set_header   X-Forwarded-For    $proxy_add_x_forwarded_for;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_pass http://tbed;
        index index.html;
    }
}
server {
    listen       443 http2;
    server_name  tbeds.xxxxx.top;

    location / {
        proxy_set_header   Host    $host;
        proxy_set_header   X-Forwarded-For    $proxy_add_x_forwarded_for;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_pass http://tbeds;
        index index.html;
    }
}
```
